### ISSUE TITLE
Les barres de progression restent à 0

### ISSUE THREAD

**Issue by mlcdf** [guillaumebriday/guillaumebriday.fr#1]
Hello,

Sur https://guillaumebriday.fr/mon-profil, les barres de progression de tes compétences restent à 0. 
Il doit y avoir un problème avec ton script ProgressBar.js.

Pour info, je suis sur Firefox 58.0 sous ElementaryOS.

**Comment by guillaumebriday** [comment]
Hey @mlcdf et merci pour ton retour ! Désolé je réponds un peu tard je n'avais pas vu ton issue.

Effectivement j'arrive à reproduire le bug même sur FF 57 et macOS mais pas à tous les coups, c'est étrange. La libraire qui détecte le scroll et celle pour gérer les progress bar ne sont pas de moi, je n'arrive pas vraiment à détecter d'où vient le problème et je n'ai pas l'erreur ailleurs. :/

A vrai dire ces progress bar vont bientôt disparaître, je ne l'ai trouve pas pertinentes.

Merci beaucoup en tout cas !
